{{- if and (eq .chezmoi.os "linux") (not .headless) -}}
{{-   range (list
      "DepartureMono"
      "IBMPlexMono"
      "IntelOneMono"
      "Iosevka"
      "IosevkaTerm"
      "JetBrainsMono"
      "Lilex"
      "ProggyClean"
      "Terminus"
      "VictorMono"
      "NerdFontsSymbolsOnly") }}
[".local/share/fonts/{{ . }}"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ . }}.tar.xz"
    exact = true
    refreshPeriod = "168h"
    include = ["SymbolsNerdFont*", "BlexMonoNerdFont-*", "DepartureMonoNerdFont-*", "IntoneMonoNerdFont-*", "IosevkaNerdFont-*", "IosevkaTermNerdFont-*", "JetBrainsMonoNerdFont-*", "LilexNerdFont-*", "ProggyClean*", "TerminessNerdFont-*", "VictorMonoNerdFont-*"]
{{-   end }}
[".local/share/fonts/Inter"]
    type = "archive"
    url = "https://github.com/rsms/inter/releases/latest/download/Inter-{{ (gitHubLatestRelease "rsms/inter").TagName | trimPrefix "v" }}.zip"
    exact = true
    refreshPeriod = "168h"
    include = ["*.ttf"]
[".local/share/fonts/CascadiaCode"]
    type = "archive"
    url = "https://github.com/microsoft/cascadia-code/releases/latest/download/CascadiaCode-{{ (gitHubLatestRelease "microsoft/cascadia-code").TagName | trimPrefix "v" }}.zip"
    stripComponents = 1
    exact = true
    refreshPeriod = "168h"
    include = ["ttf/CascadiaCodeNF*"]
{{- end}}

{{ if eq .chezmoi.os "android" -}}
[".termux/font.ttf"]
    type = "archive-file"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Iosevka.tar.xz"
    path = "IosevkaNerdFont-Regular.ttf"
    refreshPeriod = "168h"
{{- end }}
