## https://atuin.sh/docs/config/
 
auto_sync = false

## disable automatic updates, using brew instead
update_check = false
 
## possible values: auto, full, compact
style = "compact"

## enable or disable showing a preview of the selected command
## useful when the command is longer than the terminal width and is cut off
show_preview = true

# search bar on top
# invert = true

inline_height = 25
show_tabs = false
enter_accept = true

# history_filter = [
## https://docs.rs/regex/latest/regex/#syntax
## For details on the supported regular expression syntax, see
## with ^ or end with $, they'll match anywhere in the command.
## Note that these regular expressions are unanchored, i.e. if they don't start
## prevent commands matching any of these regexes from being written to history.
history_filter = [
  # common shell commands that don't need to be saved
  "^cd -",
  "^cd \\.\\.",
  "^cd$",
  "^clear$",
  "^ls$",
  "^ll$"
]

[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "apt",
  "chezmoi",
  "docker",
  "git",
  "gh",
  "go",
  "just",
  "npm",
  "pnpm",
  "podman",
  "ujust",
  "uv",
  "systemctl",
]

## Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]
