theme = "gruvbox"

[editor]
bufferline = "multiple"
line-number = "relative"
scrolloff = 10
cursorline = true
color-modes = true
auto-format = true
completion-replace = true
completion-trigger-len = 1
idle-timeout = 0
soft-wrap.enable = true
end-of-line-diagnostics = "hint"

[editor.gutters.line-numbers]
min-width = 1

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode", "diagnostics", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["selections", "file-type", "position-percentage", "total-line-numbers"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[keys.normal]
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"esc" = ["collapse_selection", "keep_primary_selection"]
"C-s" = ":write"

[keys.insert]
"C-s" = ":write"

[keys.select]
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-s" = ":write"
